target_pose_fusion_node:
  ros__parameters:
    q_acc_x: 0.16
    q_acc_y: 0.16
    q_acc_z: 0.16
    r_pos_x: 0.00000256
    r_pos_y: 0.00000256
    r_pos_z: 0.00000256

# so cua a nam
  #   target_pose_fusion_node:
  # ros__parameters:
  #   q_acc_x: 0.16
  #   q_acc_y: 0.16
  #   q_acc_z: 0.16
  #   r_pos_x: 0.00003136
  #   r_pos_y: 0.000039
  #   r_pos_z: 0.01833316



    # #    q_acc_x: 0.16
    # q_acc_y: 0.16
    # q_acc_z: 0.16
    # r_pos_xy: 0.000009
    # r_pos_z:  0.000025
    #     declare_parameter<double>("q_acc_x", 0.1);
    # declare_parameter<double>("q_acc_y", 0.1);
    # declare_parameter<double>("q_acc_z", 0.1);
    # declare_parameter<double>("r_pos_x", 0.00017956);
    # declare_parameter<double>("r_pos_y", 0.000039);
    # declare_parameter<double>("r_pos_z", 0.01833316);